[project]
name = "math-youtube-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "edge-tts>=7.2.8",
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "groq>=0.31,<1",
    "manim==0.19.0",
    "openpyxl>=3.1,<4",
    "pydantic>=2.11,<3",
    "pydantic-settings>=2.10,<3",
    "python-dotenv>=1.1,<2",
]
